### ISSUE TITLE
UI No longer works

### ISSUE THREAD

**Issue by PlayedIn** [ben423423n32j14e/zigbee2mqttadminpanel#13]
I had the zigbee2mqttadminpanel working several months.   Wanted to start using it again as I'm going to add a new zigbee2mqtt stick.   Whenever I go to https://192.168.1.38:1880/ui I get:  
`Cannot GET /ui`
https://192.168.138:1880 brings up node red without a problem.

I updated the node-red-dashboard.  That didn't help
I deleted the zigbee2mqttadminpanel flow and all the subflows.
Imported the zigbee2mqttadminpanel flow back in and corrected the mqtt settings for my setup.
I still get `Cannot GET /ui`

I'm not sure how I borked the config up, but asking for help or ideas.  Below is my node red log and also screenshots. I've been getting that length of undefined error for as long as I  can remember if I'm not mistaken.  I haven't been able to track its origin.

`Welcome to Node-RED
===================
3 Jul 21:13:12 - [info] Node-RED version: v0.20.6
3 Jul 21:13:12 - [info] Node.js  version: v10.16.0
3 Jul 21:13:12 - [info] Linux 4.14.98-v8 arm64 LE
3 Jul 21:13:13 - [info] Loading palette nodes
3 Jul 21:13:21 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
3 Jul 21:13:22 - [info] Dashboard version 2.15.5 started at /endpoint/ui
3 Jul 21:13:24 - [info] Settings file  : /etc/node-red/config.js
3 Jul 21:13:24 - [info] Context store  : 'default' [module=memory]
3 Jul 21:13:24 - [info] User directory : /config/node-red/
3 Jul 21:13:24 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Jul 21:13:24 - [info] Flows file     : /config/node-red/flows.json
3 Jul 21:13:24 - [info] Server now running at http://127.0.0.1:46836/
[21:13:24] INFO: Starting NGinx...
3 Jul 21:13:25 - [info] Starting flows
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
3 Jul 21:13:26 - [info] Started flows
3 Jul 21:13:26 - [error] [function:Format Data] TypeError: Cannot read property 'length' of undefined
3 Jul 21:13:26 - [info] [mqtt-broker:MQTT] Connected to broker: mqtt://192.168.1.38:1883
3 Jul 21:13:29 - [error] [function:Format Data] TypeError: Cannot read property 'length' of undefined
3 Jul 21:13:30 - [info] [server:Home Assistant] WebSocket Connected to http://hassio/homeassistant
[03/Jul/2019:21:21:04 -0400] 404 -(192.168.1.5) GET /ui HTTP/2.0 (Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36)
[03/Jul/2019:21:21:04 -0400] 101 -(192.168.1.5) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36)`

![image](https://user-images.githubusercontent.com/42630166/60633797-579f4d80-9dda-11e9-97a6-6f0ade5d9c2b.png)

![image](https://user-images.githubusercontent.com/42630166/60633883-b8c72100-9dda-11e9-8142-3c991968290a.png)

**Comment by PlayedIn** [comment]
Ok I found that this works: `https://192.168.1.38:1880/endpoint/ui`
and this doesn't: `https://192.168.1.38:1880/ui`

I only found this by clicking and managing to accidentally trip across an icon in settings that apparently launches the dashboard. 

I have no idea why the url requires `endpoint`.  I'll leave this open for a day or so in case anyone might explain.

**Comment by dceejay** [comment]
You have to ask the HA team why they have moved the endpoint and not made it clear.
