### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by andreapx** [ben423423n32j14e/zigbee2mqttadminpanel#18]
Hi,
how do I remove the palette that were added when I've imported the flow?
Thanks!

**Comment by robin-s-007** [comment]
Hi,
I am having the same problem.
Any help would be appreciated, as now I get configuration error messages for these modules with each deploy.
Hoping on a quick solution.

Thanks in advance

**Comment by befedi** [comment]
Hi,
I assume you have deleted the Flow and now you get the errors for e.g. the "Devices" subflow? Sadly, the subflows will not be deleted automatically. Go to menu->search flows and search for "subflow". Then you will see all subflows. Open them and at the top of the flow you can delete them.

**Comment by andreapx** [comment]
Thanks!!!
