### ISSUE TITLE
problem with dashboard

### ISSUE THREAD

**Issue by salopette** [ben423423n32j14e/zigbee2mqttadminpanel#5]
Hello, I did everything according to the instructions, but unfortunately my dashboard does not show me anything, how can I fix it?

<a href="http://www.directupload.net" target="_blank"><img src="http://fs1.directupload.net/images/181021/olsr93la.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

<a href="http://www.directupload.net" target="_blank"><img src="http://fs1.directupload.net/images/181021/syoob33b.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by orientalsniper** [comment]
Import the flow with "clipboard" using the content in https://raw.githubusercontent.com/ben423423n32j14e/zigbee2mqttadminpanel/master/flow

**Comment by salopette** [comment]
Hello, I re-imported the flow today, but my dashboard stays empty?
What am I doing wrong?

**Comment by salopette** [comment]
![sshot-2019-05-14- 2](https://user-images.githubusercontent.com/32480002/57720452-2cbe3600-7682-11e9-9f0c-3df1f5621d77.jpg)

**Comment by bobzer** [comment]
check the debug window of nodered and the log of zigbee2mqtt

**Comment by salopette** [comment]
It seems to have wrong IP, where can I change IP in Node Red?

Starting as a systemd service.
14 May 19:55:36 - [info] [mqtt-broker:MQTT] Connection failed to broker: mqtt://192.168.178.101:1883
