### ISSUE TITLE
Don't see the maps

### ISSUE THREAD

**Issue by jasimancas** [ben423423n32j14e/zigbee2mqttadminpanel#7]
Is normal that i dont see the network map?

**Comment by ben423423n32j14e** [comment]
Provide more exact information please.

**Comment by jasimancas** [comment]
![image](https://user-images.githubusercontent.com/15717847/49076682-dbd49580-f239-11e8-9fe1-87806affacbe.png)

**Comment by ben423423n32j14e** [comment]
Look on the main page, graphviz url is generated.

You need to copy the content into a graphviz viewer.

Url should be /adminpanelapi/networkmap/graphviz

There currently isn't a built in map viewing.

**Comment by jasimancas** [comment]
Ahh, ok, sorry.

Thanks!
