### ISSUE TITLE
Question from a newbie

### ISSUE THREAD

**Issue by jsponz** [ben423423n32j14e/zigbee2mqttadminpanel#8]
Hi,

I have just installed zigbee2mqtt and I want to use your dashboard. 

I am stuck at this:

4. Import flow into "Zigbee2MQTT Admin Panel" flow

Which flow should I import? I have a Philips Hue light... 

Could you help me?

Thanks!

**Comment by fred-c1** [comment]
https://github.com/ben423423n32j14e/zigbee2mqttadminpanel/blob/master/flow

**Comment by ben423423n32j14e** [comment]
Import from clipboard into a new flow you created in Node-Red called "Zigbee2MQTT Admin Panel".

<img width="564" alt="screen shot 2019-01-03 at 2 56 41 am" src="https://user-images.githubusercontent.com/3908759/50599991-c8d17700-0f03-11e9-8bf9-774a99a57365.png">

Note that Zigbee2MQTT Admin Panel is not a solution for controlling devices. It is meant as a utility for those working with Zigbee2MQTT in Node-Red. The features listed are what the control panel can currently do.

**Comment by jsponz** [comment]
Thanks for the quick reply! I works, but it is empty, although I have two lights (bulbs) managed by zigbee2mqtt.

**Comment by ben423423n32j14e** [comment]
Likely the MQTT server settings are incorrect, go into the sub flows, eg the one called "Devices" you will see the purple color node, in this instance if you double click it you can change the MQTT server IP and login details if needed.

**Comment by jsponz** [comment]
Thanks!
